/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

const INSTRUCTIONS = `Propose a new change. Interview the developer and investigate the codebase until every question raised by the ask has been answered. Only then write the artifacts.

The stop condition is not a confidence level. It is: **the open-questions set is empty** — no question remains without an answer, and the last answer generated no new questions.

---

## Phase 1: Orient

### 1.1 — Get the initial ask

If the developer has provided a description, use it. If not, ask one open question:

> "What do you want to build or change? Give me as much or as little as you have."

A one-liner is fine. The interview does the work.

### 1.2 — Read the codebase before asking anything

Based on the ask, find and read the parts of the system most likely affected. Use search tools — do not guess at file locations.

Look for:
- The models, schemas, or types involved
- The services, controllers, or handlers that would change
- Existing tests that cover this area
- Configuration or environment that affects it
- Any conventions visible in nearby code (naming, patterns, error handling)

Then scan for relevant prior art:
\`\`\`bash
ls openspec/changes/archive/
\`\`\`
Read the \`proposal.md\` of any archived change that touches the same subsystem or solves a related problem.

The goal of this reading is to understand the context well enough to ask *relevant* questions — not a generic checklist, but questions grounded in what this codebase actually looks like. Questions that code reading can already answer should not be asked.

### 1.3 — Build the initial open-questions set

From the ask and everything you've read, identify every question that would need an answer before implementation could begin without ambiguity. This is your internal working state — do not show it to the developer as a list.

The questions depend entirely on context. Domains to consider (include only those relevant to this codebase and this ask):

- **Data**: schema changes, field types, nullability, defaults for existing records, indexes, migrations
- **API / interface**: which endpoints or contracts change, request/response shape, versioning, breaking changes for consumers
- **Business logic**: validation rules, side effects, triggers, calculations, state transitions
- **Auth & permissions**: who can read or write this, role changes, visibility rules
- **Integrations**: events, webhooks, queues, external consumers, data exports
- **Frontend**: which views or components are affected, form behaviour, error states
- **Performance**: query impact, caching, load characteristics
- **Testing**: what existing tests break, what new tests are needed
- **Deployment**: migration safety, rollout strategy, rollback, feature flags

---

## Phase 2: Interview

Work through the open-questions set one question at a time until it is empty.

### For each question:

Ask it with your best guess attached:

\`\`\`
Q: <one focused question>
GUESS: <your hypothesis for the answer, and why you're guessing that>
\`\`\`

Wait for the answer before asking the next question. Never batch questions. The third question often depends on the first answer; asking them together locks in the wrong frame.

### After each answer:

1. **Mark the question resolved.**
2. **Open new questions** if the answer introduces complexity you didn't anticipate. If it points to code you haven't read, go read it before continuing — that code may generate further questions or close existing ones.
3. **Close branches** if the answer makes other questions irrelevant (e.g. "this is internal-only, no external API" closes all versioning and consumer-impact questions).
4. **Ask the next open question.**

This branching is expected and correct. The question set will grow and shrink throughout the interview. A complex answer should make the set larger, not smaller — resist the urge to move on when something surfaces new unknowns.

### Stop condition:

Stop when the open-questions set is empty: every question has an answer, and the last answer generated no new questions. Do not stop before that point.

---

## Phase 3: Confirm

When the set is empty, restate everything established in a structured summary. Use only the sections that are relevant to this change:

\`\`\`
Here's what I now understand:

What:        <what is changing, concretely>
Why:         <the problem this solves and why it matters now>
Who:         <who is affected — users, developers, downstream systems>
Data:        <schema/model changes and migration approach>
Interface:   <what changes for callers, if anything>
Logic:       <validation rules, side effects, business rules>
Permissions: <auth or visibility changes, if any>
Out of scope: <what we are explicitly not doing>

Anything wrong or missing?
\`\`\`

The gate is an explicit yes. The following are **not** yes:
- "Sounds good" → ask "Anything you'd refine?"
- "Whatever you think" → give two concrete options and ask them to pick
- Silence → ask "Did I miss anything?"

Fold corrections in and restate until you get an explicit yes.

---

## Phase 4: Artifact Creation

Once confirmed, create the change and its artifacts.

### 4.1 — Derive a name and create the change

From the confirmed summary, derive a kebab-case change name (e.g. "add expiry date to subscription" → \`add-subscription-expiry\`).

\`\`\`bash
openspec new change "<name>"
\`\`\`

### 4.2 — Get the artifact build order

\`\`\`bash
openspec status --change "<name>" --json
\`\`\`

Parse the JSON to get:
- \`applyRequires\`: artifact IDs needed before implementation
- \`artifacts\`: all artifacts with status and dependencies
- \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, \`actionContext\`: path context — use these, do not assume repo-local paths

### 4.3 — Create artifacts in dependency order

Use the **TodoWrite tool** to track progress.

For each artifact that is \`ready\` (dependencies satisfied):

1. Get instructions:
   \`\`\`bash
   openspec instructions <artifact-id> --change "<name>" --json
   \`\`\`
   The JSON includes \`context\`, \`rules\`, \`template\`, \`instruction\`, \`resolvedOutputPath\`, \`dependencies\`.

2. Read any completed dependency artifacts for context.

3. Write the artifact to \`resolvedOutputPath\`, using \`template\` as structure. Feed in:
   - Everything established in the interview (Phase 2)
   - The confirmed summary (Phase 3)
   - Codebase findings from Phase 1 and any code read during the interview
   - Relevant prior art from archived changes
   - \`context\` and \`rules\` as constraints — **never copy them into the file**

4. Show progress: "Created \`<artifact-id>\`"

Re-run \`openspec status --change "<name>" --json\` after each artifact. Stop when all \`applyRequires\` artifacts have \`status: "done"\`.

### 4.4 — Show final status

\`\`\`bash
openspec status --change "<name>"
\`\`\`

Summarise:
- Change name and location
- Artifacts created with one-line descriptions
- "Ready for implementation. Run \`/opsx:apply\` when you're ready."

---

## Guardrails

- **No fast path.** Do not proceed to artifact creation until you have an explicit confirmation of the Phase 3 summary.
- **Never skip the codebase read.** Code you haven't read is an assumption you're making. Assumptions become bugs.
- **One question at a time.** Never batch.
- **Every question needs a guess.** A question without your hypothesis is a survey, not an interview.
- **Complex answers should open new questions**, not be accepted and moved past.
- **Code reading is part of the interview**, not a separate phase — if an answer points somewhere you haven't read, go read it now.
- If a change with that name already exists, ask if the developer wants to continue it or create a new one.
- Verify each artifact file exists after writing before proceeding to the next.`;

export function getOpsxProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-propose',
    description: 'Propose a new change. Interviews the developer and investigates the codebase — one question at a time, branching on answers — until every ambiguity is resolved. Only then writes the artifacts. Use when a developer wants to turn a rough idea or ticket into a fully specified change.',
    instructions: INSTRUCTIONS,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxProposeCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Propose',
    description: 'Propose a new change — interview the developer and investigate the codebase until every ambiguity is resolved, then write the artifacts',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: INSTRUCTIONS,
  };
}
