/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getOpsxProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-propose',
    description: 'Propose a new change. Interviews the developer and investigates the codebase before writing any artifacts. Use when a developer wants to turn a rough idea or ticket into a fully specified change with proposal, design, and tasks.',
    instructions: `Propose a new change. Before writing any artifact, interview the developer and investigate the codebase until you have enough context to write something worth reading.

The output is a change directory with all artifacts ready for implementation. The path to get there runs through a focused interview, a codebase investigation, and a scan for relevant prior art — in that order.

---

## Phase 1: Interview

**Goal:** Reach ~80% confidence about what the developer actually wants, expressed in their own words.

### Step 1.1 — Get the initial input

If the developer has provided a description, use it. If not, ask one open question:

> "What do you want to build or change? Give me as much or as little as you have."

There is no minimum bar for the initial input. A one-liner is fine — the interview fills the gap.

### Step 1.2 — State a hypothesis

Before asking anything, write your current best read of what the developer wants:

\`\`\`
HYPOTHESIS: <one sentence — what you think they actually want, not just what they said>
CONFIDENCE: ~<N>% — missing: <what's still unresolved>
\`\`\`

Be honest about the number. If you can't predict their reaction to the next three questions you'd ask, the number is wrong. Always include a reason when confidence is below ~80%.

### Step 1.3 — Ask one question at a time, each with a guess

Format every question as:

\`\`\`
Q: <one focused question>
GUESS: <your hypothesis for the answer, and the reasoning behind it>
\`\`\`

Wait for the answer before asking the next question. Do not batch questions.

**What to probe for** (not necessarily in this order — follow the conversation):
- **Who** uses or is affected by this change
- **Why now** — what changed or what is currently painful
- **Success** — how they'd know it worked, with a number or observable outcome if possible
- **Constraint** — the binding limit (time, scope, backwards compatibility, performance target)
- **Out of scope** — what explicitly is not part of this change

When the developer gives convention-signaling answers ("scalable", "clean", "the usual way"), ask:
> "If you didn't have to justify this to anyone, what would you actually want?"

### Step 1.4 — Confirm intent

When confidence reaches ~80%, write back a tight restate:

\`\`\`
Here's what I now understand:

- Outcome:      <one line>
- Who:          <one line — who benefits or is affected>
- Why now:      <one line — what changed or what's painful>
- Success:      <one line — how we know it worked>
- Constraint:   <one line — the binding limit>
- Out of scope: <one line — what we're explicitly not doing>

Anything wrong or missing?
\`\`\`

The "Out of scope" line is not optional. Silent disagreement about non-goals is half of all misalignment.

The gate is an explicit confirmation. The following are **not** confirmation:
- "Whatever you think is best" → ask with two concrete options as a choice
- "Sounds good" → ask "Anything you'd refine?"
- Silence followed by "let's go" → ask "Did I miss anything?"

Fold corrections in and restate until you get an explicit yes.

---

## Phase 2: Codebase Investigation

**Goal:** Understand the existing system well enough that the artifacts reflect reality, not assumptions.

Run this phase after intent is confirmed, before writing any artifact. Do not skip it even if the developer's description was detailed.

### Step 2.1 — Locate relevant code

Based on the confirmed intent, identify and read the parts of the codebase most relevant to this change:

- Entry points, interfaces, or public APIs that will be touched
- Existing implementations of similar patterns
- Data models, schemas, or types involved
- Tests that cover the area being changed
- Configuration or environment files that affect this area

Use search tools to find files by keyword or path pattern. Read the files, don't just list them.

### Step 2.2 — Scan for relevant archived changes

\`\`\`bash
ls openspec/changes/archive/
\`\`\`

Read the \`proposal.md\` of any archived change whose name or scope overlaps with the confirmed intent. "Overlaps" means: touches the same subsystem, solves a related problem, or was explicitly mentioned by the developer.

If relevant archived changes exist, summarise what they did and note them as prior art. They become input to the artifacts — not to copy, but to avoid reinventing or contradicting.

If no archived changes are relevant, move on silently.

### Step 2.3 — Surface what you found

Before creating any artifact, tell the developer what you found in a brief summary:

\`\`\`
**Codebase context:**
- <key file or pattern you found and why it matters>
- <another finding>

**Prior art:** <archived change names, or "None relevant">

Does any of this change what you want?
\`\`\`

If something you found contradicts or complicates the confirmed intent, surface it here and re-confirm before proceeding.

---

## Phase 3: Artifact Creation

Once intent is confirmed and the codebase investigation is complete, create the change and its artifacts.

### Step 3.1 — Derive a name and create the change

From the confirmed intent, derive a kebab-case name (e.g., "add retry logic to payment processor" → \`add-payment-retry-logic\`).

\`\`\`bash
openspec new change "<name>"
\`\`\`

### Step 3.2 — Get the artifact build order

\`\`\`bash
openspec status --change "<name>" --json
\`\`\`

Parse the JSON to get:
- \`applyRequires\`: artifact IDs needed before implementation
- \`artifacts\`: all artifacts with status and dependencies
- \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, \`actionContext\`: path context — use these, do not assume repo-local paths

### Step 3.3 — Create artifacts in dependency order

Use the **TodoWrite tool** to track progress.

For each artifact that is \`ready\` (dependencies satisfied):

1. Get instructions:
   \`\`\`bash
   openspec instructions <artifact-id> --change "<name>" --json
   \`\`\`
   The JSON includes \`context\`, \`rules\`, \`template\`, \`instruction\`, \`resolvedOutputPath\`, \`dependencies\`.

2. Read any completed dependency artifacts for context.

3. Write the artifact to \`resolvedOutputPath\`, using \`template\` as structure. Incorporate:
   - The confirmed intent from Phase 1
   - The codebase findings from Phase 2
   - Any relevant prior art from archived changes
   - \`context\` and \`rules\` as constraints for you — **never copy them into the file**

4. Show progress: "Created \`<artifact-id>\`"

Re-run \`openspec status --change "<name>" --json\` after each artifact. Stop when all \`applyRequires\` artifacts have \`status: "done"\`.

### Step 3.4 — Show final status

\`\`\`bash
openspec status --change "<name>"
\`\`\`

Summarise:
- Change name and location
- Artifacts created with one-line descriptions
- "Ready for implementation. Run \`/opsx:apply\` when you're ready."

---

## Guardrails

- **Never skip the interview.** Even a fully-specified input contains assumptions. Run at least one hypothesis + confirmation cycle.
- **Never skip the codebase investigation.** Reading code before writing specs is what makes the artifacts accurate.
- **No fast path.** Do not proceed to artifact creation until you have an explicit confirmation of intent.
- **One question at a time.** Never batch questions.
- **Every question needs a guess.** A question without your hypothesis attached is a survey, not an interview.
- **Three or more rounds without confidence rising** means you're asking the wrong questions — step back and reframe.
- If a change with that name already exists, ask if the developer wants to continue it or create a new one.
- Verify each artifact file exists after writing before proceeding to the next.`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxProposeCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Propose',
    description: 'Propose a new change — interview the developer and investigate the codebase before writing any artifacts',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `Propose a new change. Before writing any artifact, interview the developer and investigate the codebase until you have enough context to write something worth reading.

The output is a change directory with all artifacts ready for implementation. The path to get there runs through a focused interview, a codebase investigation, and a scan for relevant prior art — in that order.

---

## Phase 1: Interview

**Goal:** Reach ~80% confidence about what the developer actually wants, expressed in their own words.

### Step 1.1 — Get the initial input

If the developer has provided a description (as an argument to /opsx:propose), use it. If not, ask one open question:

> "What do you want to build or change? Give me as much or as little as you have."

There is no minimum bar for the initial input. A one-liner is fine — the interview fills the gap.

### Step 1.2 — State a hypothesis

Before asking anything, write your current best read of what the developer wants:

\`\`\`
HYPOTHESIS: <one sentence — what you think they actually want, not just what they said>
CONFIDENCE: ~<N>% — missing: <what's still unresolved>
\`\`\`

Be honest about the number. If you can't predict their reaction to the next three questions you'd ask, the number is wrong. Always include a reason when confidence is below ~80%.

### Step 1.3 — Ask one question at a time, each with a guess

Format every question as:

\`\`\`
Q: <one focused question>
GUESS: <your hypothesis for the answer, and the reasoning behind it>
\`\`\`

Wait for the answer before asking the next question. Do not batch questions.

**What to probe for** (not necessarily in this order — follow the conversation):
- **Who** uses or is affected by this change
- **Why now** — what changed or what is currently painful
- **Success** — how they'd know it worked, with a number or observable outcome if possible
- **Constraint** — the binding limit (time, scope, backwards compatibility, performance target)
- **Out of scope** — what explicitly is not part of this change

When the developer gives convention-signaling answers ("scalable", "clean", "the usual way"), ask:
> "If you didn't have to justify this to anyone, what would you actually want?"

### Step 1.4 — Confirm intent

When confidence reaches ~80%, write back a tight restate:

\`\`\`
Here's what I now understand:

- Outcome:      <one line>
- Who:          <one line — who benefits or is affected>
- Why now:      <one line — what changed or what's painful>
- Success:      <one line — how we know it worked>
- Constraint:   <one line — the binding limit>
- Out of scope: <one line — what we're explicitly not doing>

Anything wrong or missing?
\`\`\`

The "Out of scope" line is not optional. Silent disagreement about non-goals is half of all misalignment.

The gate is an explicit confirmation. The following are **not** confirmation:
- "Whatever you think is best" → ask with two concrete options as a choice
- "Sounds good" → ask "Anything you'd refine?"
- Silence followed by "let's go" → ask "Did I miss anything?"

Fold corrections in and restate until you get an explicit yes.

---

## Phase 2: Codebase Investigation

**Goal:** Understand the existing system well enough that the artifacts reflect reality, not assumptions.

Run this phase after intent is confirmed, before writing any artifact. Do not skip it even if the developer's description was detailed.

### Step 2.1 — Locate relevant code

Based on the confirmed intent, identify and read the parts of the codebase most relevant to this change:

- Entry points, interfaces, or public APIs that will be touched
- Existing implementations of similar patterns
- Data models, schemas, or types involved
- Tests that cover the area being changed
- Configuration or environment files that affect this area

Use search tools to find files by keyword or path pattern. Read the files, don't just list them.

### Step 2.2 — Scan for relevant archived changes

\`\`\`bash
ls openspec/changes/archive/
\`\`\`

Read the \`proposal.md\` of any archived change whose name or scope overlaps with the confirmed intent. "Overlaps" means: touches the same subsystem, solves a related problem, or was explicitly mentioned by the developer.

If relevant archived changes exist, summarise what they did and note them as prior art. They become input to the artifacts — not to copy, but to avoid reinventing or contradicting.

If no archived changes are relevant, move on silently.

### Step 2.3 — Surface what you found

Before creating any artifact, tell the developer what you found in a brief summary:

\`\`\`
**Codebase context:**
- <key file or pattern you found and why it matters>
- <another finding>

**Prior art:** <archived change names, or "None relevant">

Does any of this change what you want?
\`\`\`

If something you found contradicts or complicates the confirmed intent, surface it here and re-confirm before proceeding.

---

## Phase 3: Artifact Creation

Once intent is confirmed and the codebase investigation is complete, create the change and its artifacts.

### Step 3.1 — Derive a name and create the change

From the confirmed intent, derive a kebab-case name (e.g., "add retry logic to payment processor" → \`add-payment-retry-logic\`).

\`\`\`bash
openspec new change "<name>"
\`\`\`

### Step 3.2 — Get the artifact build order

\`\`\`bash
openspec status --change "<name>" --json
\`\`\`

Parse the JSON to get:
- \`applyRequires\`: artifact IDs needed before implementation
- \`artifacts\`: all artifacts with status and dependencies
- \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, \`actionContext\`: path context — use these, do not assume repo-local paths

### Step 3.3 — Create artifacts in dependency order

Use the **TodoWrite tool** to track progress.

For each artifact that is \`ready\` (dependencies satisfied):

1. Get instructions:
   \`\`\`bash
   openspec instructions <artifact-id> --change "<name>" --json
   \`\`\`
   The JSON includes \`context\`, \`rules\`, \`template\`, \`instruction\`, \`resolvedOutputPath\`, \`dependencies\`.

2. Read any completed dependency artifacts for context.

3. Write the artifact to \`resolvedOutputPath\`, using \`template\` as structure. Incorporate:
   - The confirmed intent from Phase 1
   - The codebase findings from Phase 2
   - Any relevant prior art from archived changes
   - \`context\` and \`rules\` as constraints for you — **never copy them into the file**

4. Show progress: "Created \`<artifact-id>\`"

Re-run \`openspec status --change "<name>" --json\` after each artifact. Stop when all \`applyRequires\` artifacts have \`status: "done"\`.

### Step 3.4 — Show final status

\`\`\`bash
openspec status --change "<name>"
\`\`\`

Summarise:
- Change name and location
- Artifacts created with one-line descriptions
- "Ready for implementation. Run \`/opsx:apply\` when you're ready."

---

## Guardrails

- **Never skip the interview.** Even a fully-specified input contains assumptions. Run at least one hypothesis + confirmation cycle.
- **Never skip the codebase investigation.** Reading code before writing specs is what makes the artifacts accurate.
- **No fast path.** Do not proceed to artifact creation until you have an explicit confirmation of intent.
- **One question at a time.** Never batch questions.
- **Every question needs a guess.** A question without your hypothesis attached is a survey, not an interview.
- **Three or more rounds without confidence rising** means you're asking the wrong questions — step back and reframe.
- If a change with that name already exists, ask if the developer wants to continue it or create a new one.
- Verify each artifact file exists after writing before proceeding to the next.`
  };
}
